import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/templates/ThemeProvider";
import { NavigationBar } from "@/components/organisms/NavigationBar";
import { cn } from "@/utils/cn";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(nunito.className, "pb-6 dark:bg-very-dark-blue")}
            >
                <ThemeProvider>
                    <NavigationBar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
